// Short sandbag
PDO_SANDBAG_SHORT_COST = 50;
PDO_SANDBAG_SHORT_NAME = format["Short sandbag (%1sp)", PDO_SANDBAG_SHORT_COST];

// Long sandbag
PDO_SANDBAG_LONG_COST = 100;
PDO_SANDBAG_LONG_NAME = format["Long sandbag (%1sp)", PDO_SANDBAG_LONG_COST];

// Round sandbag
PDO_SANDBAG_ROUND_COST = 150;
PDO_SANDBAG_ROUND_NAME = format["Round sandbag (%1sp)", PDO_SANDBAG_ROUND_COST];

// Corner sandbag
PDO_SANDBAG_CORNER_COST = 25;
PDO_SANDBAG_CORNER_NAME = format["Corner sandbag (%1sp)", PDO_SANDBAG_CORNER_COST];

// 3YA40 crate (AK-74M mags)
PDO_CRATE_3YA40_COST = 500;
PDO_CRATE_3YA40_NAME = format["Crate: 3YA40 (%1sp)", PDO_CRATE_3YA40_COST];

// 7YA37 crate (AK-74Ms +  mags)
PDO_CRATE_7YA37_COST = 750;
PDO_CRATE_7YA37_NAME = format["Crate: 7YA37 (%1sp)", PDO_CRATE_7YA37_COST];

// Ammo crate
PDO_CRATE_AMMO_COST = 1000;
PDO_CRATE_AMMO_NAME = format["Crate: ammo (%1sp)", PDO_CRATE_AMMO_COST];

// Launcher crate
PDO_CRATE_LAUNCHER_COST = 1500;
PDO_CRATE_LAUNCHER_NAME = format["Crate: launchers (%1sp)", PDO_CRATE_LAUNCHER_COST];

// Special weapons crate
PDO_CRATE_SPECIALW_COST = 2000;
PDO_CRATE_SPECIALW_NAME = format["Crate: special weapons (%1sp)", PDO_CRATE_SPECIALW_COST];

// Artillery: flares
PDO_ARTY_FLARE_COST = 25;
PDO_ARTY_FLARE_NAME = format["Artillery: flare (%1sp)", PDO_ARTY_FLARE_COST];

// Artillery: smoke
PDO_ARTY_SMOKE_COST = 150;
PDO_ARTY_SMOKE_NAME = format["Artillery: Smoke (%1sp)", PDO_ARTY_SMOKE_COST];

// Artillery: HE
PDO_ARTY_HE_COST = 250;
PDO_ARTY_HE_NAME = format["Artillery: HE (%1sp)", PDO_ARTY_HE_COST];

// Artillery: GRAD
PDO_ARTY_GRAD_COST = 1000;
PDO_ARTY_GRAD_NAME = format["Artillery: GRAD (%1sp)", PDO_ARTY_GRAD_COST];

PDO_NAMES = [PDO_SANDBAG_SHORT_NAME
			,PDO_SANDBAG_LONG_NAME
			,PDO_SANDBAG_ROUND_NAME
			,PDO_SANDBAG_CORNER_NAME
			,PDO_CRATE_3YA40_NAME
			,PDO_CRATE_7YA37_NAME
			,PDO_CRATE_AMMO_NAME
			,PDO_CRATE_LAUNCHER_NAME
			,PDO_CRATE_SPECIALW_NAME
			,PDO_ARTY_FLARE_NAME
			,PDO_ARTY_SMOKE_NAME
			,PDO_ARTY_HE_NAME
			,PDO_ARTY_GRAD_NAME
			];

PDO_COSTS = [PDO_SANDBAG_SHORT_COST
			,PDO_SANDBAG_LONG_COST
			,PDO_SANDBAG_ROUND_COST
			,PDO_SANDBAG_CORNER_COST
			,PDO_CRATE_3YA40_COST
			,PDO_CRATE_7YA37_COST
			,PDO_CRATE_AMMO_COST
			,PDO_CRATE_LAUNCHER_COST
			,PDO_CRATE_SPECIALW_COST					
			,PDO_ARTY_FLARE_COST
			,PDO_ARTY_SMOKE_COST
			,PDO_ARTY_HE_COST
			,PDO_ARTY_GRAD_COST	
			];


// String resources
PD_STR_HEADER = "Resupplying";
PD_STR_AVAILABLE_SUPPLY_POINTS = "<t font='PuristaBold'>Available supply points:</t>";
PD_STR_SElECT_SUPPLY_OPTION = "<t font='PuristaBold'>Select supply option:</t>";
PD_STR_PURCHASE_BUTTON = "<t font='PuristaBold'>Purchase</t>";