// Short sandbag
PDO_SANDBAG_SHORT_COST = 50;
PDO_SANDBAG_SHORT_NAME = format["Short sandbag (%1sp)", PDO_SANDBAG_SHORT_COST];

// Long sandbag
PDO_SANDBAG_LONG_COST = 100;
PDO_SANDBAG_LONG_NAME = format["Long sandbag (%1sp)", PDO_SANDBAG_LONG_COST];

// Round sandbag
PDO_SANDBAG_ROUND_COST = 150;
PDO_SANDBAG_ROUND_NAME = format["Round sandbag (%1sp)", PDO_SANDBAG_ROUND_COST];

// Corner sandbag
PDO_SANDBAG_CORNER_COST = 25;
PDO_SANDBAG_CORNER_NAME = format["Corner sandbag (%1sp)", PDO_SANDBAG_CORNER_COST];

// Artillery: flares
PDO_ARTY_FLARE_COST = 25;
PDO_ARTY_FLARE_NAME = format["Artillery: flare (%1sp)", PDO_ARTY_FLARE_COST];

// Artillery: smoke
PDO_ARTY_SMOKE_COST = 150;
PDO_ARTY_SMOKE_NAME = format["Artillery: Smoke (%1sp)", PDO_ARTY_SMOKE_COST];

// Artillery: HE
PDO_ARTY_HE_COST = 250;
PDO_ARTY_HE_NAME = format["Artillery: HE (%1sp)", PDO_ARTY_HE_COST];

// Artillery: GRAD
PDO_ARTY_GRAD_COST = 1000;
PDO_ARTY_GRAD_NAME = format["Artillery: GRAD (%1sp)", PDO_ARTY_GRAD_COST];

PDO_NAMES = [PDO_SANDBAG_SHORT_NAME
			,PDO_SANDBAG_LONG_NAME
			,PDO_SANDBAG_ROUND_NAME
			,PDO_SANDBAG_CORNER_NAME
			,PDO_ARTY_FLARE_NAME
			,PDO_ARTY_SMOKE_NAME
			,PDO_ARTY_HE_NAME
			,PDO_ARTY_GRAD_NAME
			];

PDO_COSTS = [PDO_SANDBAG_SHORT_COST
			,PDO_SANDBAG_LONG_COST
			,PDO_SANDBAG_ROUND_COST
			,PDO_SANDBAG_CORNER_COST					
			,PDO_ARTY_FLARE_COST
			,PDO_ARTY_SMOKE_COST
			,PDO_ARTY_HE_COST
			,PDO_ARTY_GRAD_COST	
			];	